name: Bug Report
description: Report a bug in Spark Intelligence
title: "[bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Security/safety issues: do NOT file public issues. Follow `SECURITY.md`.
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "Windows 11 / macOS 14 / Ubuntu 22.04"
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: "3.10.x"
    validations:
      required: true
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: What did you expect to happen, and what happened instead?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps. If it only happens sometimes, say how often.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: health
    attributes:
      label: `spark health` output
      render: shell
    validations:
      required: true
  - type: textarea
    id: services
    attributes:
      label: `spark services` output
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs (last 50-200 lines)
      description: From `~/.spark/logs` (redact secrets).
      render: shell
    validations:
      required: false

