# Business Ops Chip (runtime)

chip:
  id: biz-ops
  name: Business Ops Intelligence
  version: 0.1.0
  description: |
    Learns operational and pricing signals with clear ethics and transparency.
  author: Vibeship
  license: MIT
  human_benefit: "Improve operational clarity and sustainable decision-making."
  harm_avoidance:
    - "No deceptive pricing tactics"
    - "No falsified reporting"
  risk_level: medium
  safety_tests:
    - "no_deceptive_pricing"
    - "no_false_reporting"
  domains:
    - business_ops
    - strategy
    - pricing

triggers:
  patterns:
    - "pricing experiment"
    - "pricing test"
    - "revenue forecast"
    - "runway"
    - "ops brief"
    - "operational risk"
    - "budget forecast"
  events:
    - "post_tool"
    - "post_tool_failure"
    - "user_prompt"
    - "PostToolUse"
    - "PostToolUseFailure"
    - "UserPromptSubmit"
    - "pricing_experiment"
    - "forecast_created"
    - "ops_plan"
  tools:
    - name: Edit
      context_contains:
        - "pricing"
        - "pricing experiment"
        - "forecast"
        - "runway"
        - "budget"
        - "ops brief"
        - "operational"
        - "dependency"
        - "risk"
        - "assumption"
        - "revenue"
        - "burn"
        - "variant"
        - "segment"
    - name: Write
      context_contains:
        - "pricing"
        - "pricing experiment"
        - "forecast"
        - "runway"
        - "budget"
        - "ops brief"
        - "operational"
        - "dependency"
        - "risk"
        - "assumption"
        - "revenue"
        - "burn"
        - "variant"
        - "segment"
    - name: Read
      context_contains:
        - "pricing"
        - "pricing experiment"
        - "forecast"
        - "runway"
        - "budget"
        - "ops brief"
        - "operational"
        - "dependency"
        - "risk"
        - "assumption"
        - "revenue"
        - "burn"
        - "variant"
        - "segment"
    - name: Bash
      context_contains:
        - "pricing"
        - "forecast"
        - "runway"
        - "budget"
        - "revenue"
        - "burn"

observers:
  - name: ops_brief
    description: Tracks operational brief and risks
    triggers: ["ops brief", "operational risk", "ops dependency", "operational dependency", "ops dependencies", "operational dependencies"]
    capture:
      required:
        owner: "Owner or team"
        risk: "Key risk"
      optional:
        dependency: "Dependency"
        mitigation: "Mitigation plan"
    extraction:
      - field: owner
        patterns:
          - "\\bowner\\b\\s*[:=]\\s*(.+)"
          - "\\bteam\\b\\s*[:=]\\s*(.+)"
      - field: risk
        patterns:
          - "\\brisk\\b\\s*[:=]\\s*(.+)"
      - field: dependency
        patterns:
          - "\\bdependency\\b\\s*[:=]\\s*(.+)"
      - field: mitigation
        patterns:
          - "\\bmitigation\\b\\s*[:=]\\s*(.+)"

  - name: pricing_experiment
    description: Tracks pricing experiment setup
    triggers: ["pricing experiment", "pricing test", "pricing plan", "pricing variant", "experiment plan"]
    capture:
      required:
        variant_id: "Pricing variant"
        target_segment: "Target segment"
      optional:
        price_point: "Price point"
        duration: "Experiment duration"
        success_metric: "Success metric"
    extraction:
      - field: variant_id
        patterns:
          - "\\bvariant\\b\\s*#?\\s*([A-Za-z0-9_-]+)"
          - "variant_id\\s*[:=]\\s*([A-Za-z0-9_-]+)"
      - field: target_segment
        patterns:
          - "\\bsegment\\b\\s*[:=]\\s*(.+)"
      - field: price_point
        patterns:
          - "\\bprice\\s*point\\b\\s*[:=]\\s*(.+)"
      - field: duration
        patterns:
          - "\\bduration\\b\\s*[:=]\\s*(.+)"
      - field: success_metric
        patterns:
          - "\\bsuccess\\s*metric\\b\\s*[:=]\\s*(.+)"

  - name: forecast
    description: Tracks forecast assumptions and outputs
    triggers: ["forecast", "runway", "forecast assumptions", "revenue projection", "burn projection"]
    capture:
      required:
        horizon: "Forecast horizon"
        assumption: "Key assumption"
      optional:
        revenue: "Projected revenue"
        burn: "Projected burn"
    extraction:
      - field: horizon
        patterns:
          - "\\bhorizon\\b\\s*[:=]\\s*(.+)"
      - field: assumption
        patterns:
          - "\\bassumption\\b\\s*[:=]\\s*(.+)"
        keywords:
          missing: ["assumption missing", "assumptions missing", "no assumption", "assumption: tbd", "assumptions: tbd", "assumption unknown"]
      - field: revenue
        patterns:
          - "\\brevenue\\b\\s*[:=]\\s*(.+)"
      - field: burn
        patterns:
          - "\\bburn\\b\\s*[:=]\\s*(.+)"

outcomes:
  positive:
    - condition: "success_metric == retention"
      insight: "Pricing experiment uses retention metric"
      weight: 1.0
  negative:
    - condition: "assumption == missing"
      insight: "Forecast missing assumptions"
      weight: 1.0

questions:
  - id: pricing_ethics
    question: "What pricing behaviors are off-limits for this business?"
    category: safety
    phase: discovery
    required: true
    affects_learning: ["pricing_experiment"]
  - id: ops_success
    question: "Which operational outcomes matter most for this sprint?"
    category: operations
    phase: discovery
    required: true
    affects_learning: ["ops_brief", "forecast"]
