# Game Dev Chip (runtime)

chip:
  id: game_dev
  name: Game Dev Intelligence
  version: 0.2.0
  activation: opt_in
  description: |
    Learns gameplay, balance, and retention signals to improve player outcomes.
  author: Vibeship
  license: MIT
  human_benefit: "Improve player experience without exploitation or harm."
  harm_avoidance:
    - "No manipulative or addictive dark patterns"
    - "No harmful or abusive content strategies"
  risk_level: medium
  safety_tests:
    - "no_dark_patterns"
    - "no_harmful_content"
  domains:
    - game_dev
    - gameplay
    - balance
    - retention
    - player_experience

triggers:
  patterns:
    - "playtest"
    - "core loop"
    - "balance"
    - "difficulty"
    - "retention"
    - "frustrating"
    - "not fun"
  events:
    - "post_tool"
    - "post_tool_failure"
    - "user_prompt"
    - "PostToolUse"
    - "PostToolUseFailure"
    - "UserPromptSubmit"
    - "playtest_result"
    - "balance_change"
    - "build_released"
    - "bug_reported"
    - "user_feedback"
  tools:
    - name: Edit
      context_contains:
        - "game"
        - "playtest"
        - "balance"
        - "difficulty"
        - "retention"
        - "churn"
        - "session length"
        - "loot"
        - "drop rate"
        - "combat"
        - "enemy"
        - "player"
        - "level"
        - "unity"
        - "unreal"
        - "godot"
        - ".unity"
        - ".uproject"
        - ".tscn"
        - ".gd"
        - ".cs"
        - ".cpp"
        - "assets/"
    - name: Write
      context_contains:
        - "game"
        - "playtest"
        - "balance"
        - "difficulty"
        - "retention"
        - "churn"
        - "session length"
        - "loot"
        - "drop rate"
        - "combat"
        - "enemy"
        - "player"
        - "level"
        - "unity"
        - "unreal"
        - "godot"
        - ".unity"
        - ".uproject"
        - ".tscn"
        - ".gd"
        - ".cs"
        - ".cpp"
        - "assets/"
    - name: Read
      context_contains:
        - "game"
        - "playtest"
        - "balance"
        - "difficulty"
        - "retention"
        - "churn"
        - "session length"
        - "loot"
        - "drop rate"
        - "combat"
        - "enemy"
        - "player"
        - "level"
        - "unity"
        - "unreal"
        - "godot"
        - ".unity"
        - ".uproject"
        - ".tscn"
        - ".gd"
        - ".cs"
        - ".cpp"
        - "assets/"
    - name: Bash
      context_contains:
        - "unity"
        - "unreal"
        - "godot"
        - "build"
        - "playtest"
        - "assets"
        - "scene"

observers:
  - name: playtest_feedback
    description: Captures playtest feedback and satisfaction
    triggers: ["playtest", "feedback", "frustrating", "not fun"]
    capture:
      required:
        playtest_id: "Playtest identifier"
        rating: "Player rating (1-5)"
      optional:
        segment: "Player segment"
        notes: "Summary of feedback"
    extraction:
      - field: playtest_id
        patterns:
          - "playtest\\s*#?\\s*([A-Za-z0-9_-]+)"
      - field: rating
        patterns:
          - "rating\\s*[:=]?\\s*([1-5])"
          - "([1-5])\\s*/\\s*5"
      - field: segment
        patterns:
          - "segment\\s*[:=]\\s*([A-Za-z0-9_-]+)"
      - field: notes
        patterns:
          - "feedback\\s*[:=]\\s*(.+)"

  - name: balance_change
    description: Tracks balance and tuning changes
    triggers: ["balance", "tuning", "difficulty", "drop rate"]
    capture:
      required:
        system: "System tuned (economy, combat, rewards)"
        change: "Description of the change"
      optional:
        before: "Previous value"
        after: "New value"
    extraction:
      - field: system
        keywords:
          combat: ["combat", "damage", "enemy"]
          economy: ["economy", "currency", "gold"]
          rewards: ["reward", "loot", "drop rate"]
          difficulty: ["difficulty", "hard", "easy"]
      - field: change
        patterns:
          - "change\\s*[:=]\\s*(.+)"
          - "tuned\\s+(.+)"
          - "balance\\s+(.+)"
      - field: before
        patterns:
          - "before\\s*[:=]\\s*(\\S+)"
      - field: after
        patterns:
          - "after\\s*[:=]\\s*(\\S+)"

  - name: retention_metric
    description: Tracks retention and engagement signals
    triggers: ["retention", "session length", "churn"]
    capture:
      required:
        metric_name: "Metric name"
        metric_value: "Metric value"
      optional:
        period: "Time window"
    extraction:
      - field: metric_name
        keywords:
          D1: ["d1", "day 1", "day1"]
          D7: ["d7", "day 7", "day7"]
          D30: ["d30", "day 30", "day30"]
          retention: ["retention"]
          churn: ["churn"]
      - field: metric_value
        patterns:
          - "(?:retention|churn|session length)\\s*[:=]?\\s*(\\d+(?:\\.\\d+)?)(?:\\s*%|\\b)"
      - field: period
        patterns:
          - "period\\s*[:=]\\s*([A-Za-z0-9_-]+)"

outcomes:
  positive:
    - condition: "metric_value > 0.3"
      insight: "Retention above target threshold"
      weight: 1.0
  negative:
    - condition: "rating < 3"
      insight: "Playtest satisfaction below acceptable level"
      weight: 1.0

questions:
  - id: core_loop
    question: "What is the core loop and how do we measure if it feels good?"
    category: goal
    phase: discovery
    required: true
    affects_learning: ["playtest_feedback"]
  - id: target_retention
    question: "What retention target matters most (D1, D7, D30)?"
    category: metric
    phase: discovery
    required: false
    affects_learning: ["retention_metric"]
  - id: difficulty_intent
    question: "What difficulty curve do we want players to experience?"
    category: quality
    phase: prototype
    required: false
    affects_learning: ["balance_change"]
