# Marketing Chip (runtime)

chip:
  id: marketing
  name: Marketing Intelligence
  version: 0.1.0
  description: |
    Learns campaign, funnel, and messaging signals while avoiding manipulation.
  author: Vibeship
  license: MIT
  human_benefit: "Improve marketing clarity and outcomes without harm."
  harm_avoidance:
    - "No deceptive or manipulative claims"
    - "No dark-pattern retention tactics"
  risk_level: medium
  safety_tests:
    - "no_deceptive_claims"
    - "no_dark_patterns"
  domains:
    - marketing
    - growth
    - messaging

triggers:
  patterns:
    - "campaign"
    - "funnel"
    - "landing page"
    - "headline"
    - "ad copy"
    - "positioning"
    - "ctr"
    - "cpc"
    - "cac"
    - "roas"
  events:
    - "post_tool"
    - "post_tool_failure"
    - "user_prompt"
    - "PostToolUse"
    - "PostToolUseFailure"
    - "UserPromptSubmit"
    - "campaign_brief"
    - "ad_copy_created"
    - "experiment_defined"
  tools:
    - name: Edit
      context_contains:
        - "campaign"
        - "funnel"
        - "landing page"
        - "landing"
        - "headline"
        - "ad copy"
        - "cta"
        - "positioning"
        - "value prop"
        - "ad variant"
        - "copy variant"
        - "marketing/"
    - name: Write
      context_contains:
        - "campaign"
        - "funnel"
        - "landing page"
        - "landing"
        - "headline"
        - "ad copy"
        - "cta"
        - "positioning"
        - "value prop"
        - "ad variant"
        - "copy variant"
        - "marketing/"
    - name: Read
      context_contains:
        - "campaign"
        - "funnel"
        - "landing page"
        - "landing"
        - "headline"
        - "ad copy"
        - "cta"
        - "positioning"
        - "value prop"
        - "ad variant"
        - "copy variant"
        - "marketing/"
    - name: Bash
      context_contains:
        - "utm"
        - "ga4"
        - "analytics"
        - "ctr"
        - "cpc"
        - "cac"
        - "roas"
        - "conversion"

observers:
  - name: campaign_brief
    description: Tracks campaign positioning and target audience
    triggers: ["campaign brief", "positioning", "target audience", "value prop"]
    capture:
      required:
        product: "Product or offer"
        audience: "Target audience"
      optional:
        channel: "Primary channel"
        value_prop: "Value proposition"
        budget: "Budget range"
    extraction:
      - field: product
        patterns:
          - "product\\s*[:=]\\s*(.+)"
      - field: audience
        patterns:
          - "audience\\s*[:=]\\s*(.+)"
      - field: channel
        keywords:
          email: ["email", "newsletter"]
          search: ["search", "google", "bing"]
          social: ["social", "meta", "facebook", "instagram", "tiktok", "linkedin"]
      - field: value_prop
        patterns:
          - "value\\s*prop\\s*[:=]\\s*(.+)"
      - field: budget
        patterns:
          - "budget\\s*[:=]\\s*(.+)"

  - name: ad_copy
    description: Tracks ad copy variants and messaging
    triggers: ["ad copy", "headline", "cta", "ad variant", "copy variant"]
    capture:
      required:
        channel: "Distribution channel"
        variant_id: "Variant identifier"
      optional:
        headline: "Headline text"
        cta: "Call to action"
        claim: "Primary claim"
    extraction:
      - field: channel
        keywords:
          email: ["email", "newsletter"]
          search: ["search", "google", "bing"]
          social: ["social", "meta", "facebook", "instagram", "tiktok", "linkedin"]
      - field: variant_id
        patterns:
          - "variant\\s*#?\\s*([A-Za-z0-9_-]+)"
          - "variant_id\\s*[:=]\\s*([A-Za-z0-9_-]+)"
      - field: headline
        patterns:
          - "headline\\s*[:=]\\s*(.+)"
      - field: cta
        patterns:
          - "cta\\s*[:=]\\s*(.+)"
      - field: claim
        patterns:
          - "claim\\s*[:=]\\s*(.+)"

  - name: funnel_metric
    description: Tracks funnel metrics and performance
    triggers: ["ctr", "cpc", "cac", "roas", "conversion rate"]
    capture:
      required:
        metric_name: "Metric name"
        metric_value: "Metric value"
      optional:
        channel: "Channel"
        time_window: "Time window"
    extraction:
      - field: metric_name
        keywords:
          CTR: ["ctr"]
          CPC: ["cpc"]
          CAC: ["cac"]
          ROAS: ["roas"]
          conversion_rate: ["conversion rate"]
      - field: metric_value
        patterns:
          - "(?:ctr|cpc|cac|roas|conversion rate)\\s*[:=]?\\s*(\\d+(?:\\.\\d+)?)(?:\\s*%|\\b)"
      - field: channel
        keywords:
          email: ["email", "newsletter"]
          search: ["search", "google", "bing"]
          social: ["social", "meta", "facebook", "instagram", "tiktok", "linkedin"]
      - field: time_window
        patterns:
          - "time\\s*window\\s*[:=]\\s*(.+)"

outcomes:
  positive:
    - condition: "metric_name == CTR"
      insight: "CTR reported"
      weight: 1.0
    - condition: "metric_name == ROAS"
      insight: "ROAS reported"
      weight: 1.0
  negative:
    - condition: "metric_name == CAC and metric_value > 200"
      insight: "CAC too high"
      weight: 1.0

questions:
  - id: messaging_guardrails
    question: "What claims are safe and verifiable for this campaign?"
    category: safety
    phase: discovery
    required: true
    affects_learning: ["ad_copy", "campaign_brief"]
  - id: success_metrics
    question: "Which metrics define success and what thresholds are acceptable?"
    category: performance
    phase: discovery
    required: true
    affects_learning: ["funnel_metric"]
