# ~/.spark/chips/social-convo.chip.yaml
# Spark Chip for Conversation Intelligence on X/Twitter

# ============================================================
# IDENTITY: Who is this chip?
# ============================================================
chip:
  id: social-convo
  name: X Conversation Intelligence
  version: 1.0.0
  activation: opt_in
  description: |
    Makes Spark intelligent about X/Twitter conversations.
    Learns reply patterns, conversation hooks, thread DNA,
    and what styles generate genuine engagement.

    Not about gaming the algorithm. About being genuinely
    interesting in conversation.

  author: Vibeship
  license: MIT

  human_benefit: "Help create more thoughtful, engaging conversations online."
  harm_avoidance:
    - "No manipulation or engagement farming"
    - "No rage-bait or divisive tactics"
    - "No fake engagement patterns"
  risk_level: low
  safety_tests:
    - "no_manipulation"
    - "no_rage_bait"

  agent:
    name: Spark
    description: |
      Spark observes conversation patterns on X, learns what
      makes replies land, and develops genuine conversational skill.
    personality:
      - witty
      - genuine
      - curious
      - sharp

  domains:
    - x-conversation
    - reply-strategy
    - engagement
    - conversation-dna
    - hooks

# ============================================================
# TRIGGERS: What activates this chip?
# ============================================================
triggers:
  patterns:
    - "x reply"
    - "tweet reply"
    - "reply to tweet"
    - "tweet engagement"
    - "reply strategy"
    - "conversation hook"
    - "quote tweet"
    - "thread reply"
    - "conversation dna"
    - "high engagement reply"

  events:
    - post_tool
    - post_tool_failure
    - user_prompt
    - PostToolUse
    - PostToolUseFailure
    - UserPromptSubmit
    - x_reply_sent
    - x_reply_received
    - x_conversation_analyzed
    - x_hook_detected
    - x_dna_extracted

  tools:
    - name: mcp__x-twitter__post_tweet
      context_contains: ["reply", "respond", "answer", "thread"]
    - name: mcp__x-twitter__get_tweet_details
      context_contains: ["reply", "conversation", "thread"]
    - name: mcp__x-twitter__search_twitter
      context_contains: ["reply", "engagement", "conversation"]

# ============================================================
# OBSERVERS: What data to capture when triggered?
# ============================================================
observers:
  # Reply Sent Observer
  - name: reply_sent
    description: Captures when Spark sends a reply on X

    triggers:
      - "x reply sent"
      - "replied to tweet"
      - "posted reply"

    capture:
      required:
        tweet_id: "ID of the reply tweet"
        reply_to_id: "ID of the tweet being replied to"
        tone_used: "witty / technical / conversational / provocative"

      optional:
        hook_type: "question / observation / challenge / agreement / addition"
        content: "Reply text"
        author_handle: "Who we replied to"
        thread_depth: "Position in thread (1=direct reply)"
        had_personality_snippet: "Whether personality was injected"

    extraction:
      - field: tone_used
        keywords:
          witty: ["witty", "funny", "humor", "joke", "ironic"]
          technical: ["technical", "code", "explain", "detail", "data"]
          conversational: ["casual", "chat", "hey", "nice"]
          provocative: ["bold", "challenge", "disagree", "hot take"]

      - field: hook_type
        keywords:
          question: ["?", "what", "how", "why", "curious"]
          observation: ["noticed", "interesting", "pattern", "seems"]
          challenge: ["disagree", "actually", "but", "counter"]
          agreement: ["exactly", "this", "agree", "yes"]
          addition: ["also", "adding", "plus", "and"]

  # Reply Effectiveness Observer
  - name: reply_effectiveness
    description: Tracks how well replies performed

    triggers:
      - "reply engagement"
      - "reply performance"
      - "reply metrics"

    capture:
      required:
        tweet_id: "Which reply"
        outcome_type: "positive / negative / neutral"

      optional:
        likes: "Number of likes"
        replies_received: "Number of replies to our reply"
        author_responded: "Did the original author respond"
        quote_tweets: "Number of quote tweets"
        impressions: "Number of impressions"
        warmth_change: "Did this change user warmth level"

  # High Engagement Reply Observed
  - name: high_engagement_reply_observed
    description: Captures high-performing replies by anyone for pattern learning

    triggers:
      - "high engagement reply"
      - "viral reply"
      - "great reply observed"

    capture:
      required:
        content: "Reply text"
        engagement: "Total engagement score"

      optional:
        hook_type: "How the reply opened"
        structure: "Short / medium / long / threaded"
        tone: "Tone classification"
        author_handle: "Who wrote it"
        parent_tweet_topic: "What the parent tweet was about"
        why_it_worked: "Analysis of why this reply resonated"

  # Emotional Trigger Analysis Observer
  - name: emotional_trigger
    description: |
      Detects which psychological triggers are present in content.
      Goes beyond tone (witty/technical) to the emotional mechanism
      underneath. Based on behavioral psychology research.

    triggers:
      - "tweet"
      - "reply"
      - "posted"
      - "engagement"

    capture:
      required:
        content: "The tweet or reply text"

      optional:
        primary_trigger: "curiosity_gap / surprise / validation / vulnerability / aspiration / contrast / identity_signal"
        secondary_trigger: "Additional emotional trigger if layered"
        psychological_mechanism: "Why this works on people"
        trigger_strength: "subtle / moderate / strong"
        ethical_check: "Is this trigger manipulative or genuine?"

    extraction:
      - field: primary_trigger
        keywords:
          curiosity_gap: ["nobody tells you", "here's what", "the thing about", "turns out", "actually"]
          surprise: ["unexpected", "counter-intuitive", "wrong about", "changed my mind", "plot twist"]
          validation: ["you're right", "exactly this", "finally someone", "not just me", "we all know"]
          vulnerability: ["I was wrong", "I don't know", "failed", "mistake", "struggling", "honestly"]
          aspiration: ["imagine", "what if", "possible", "could be", "path to", "how I went from"]
          contrast: ["vs", "instead", "but actually", "common advice", "everyone thinks", "real difference"]
          identity_signal: ["real builders", "if you know", "we don't", "our kind", "unlike most"]

      - field: trigger_strength
        keywords:
          strong: ["never", "always", "everything", "nobody", "completely", "the only"]
          moderate: ["usually", "often", "most", "many", "the key"]
          subtle: ["maybe", "sometimes", "slight", "small", "interesting"]

  # Conversation Psychology Observer
  - name: conversation_psychology
    description: |
      Tracks the psychological dynamics of conversations.
      Reciprocity, social proof, open loops, barrier reduction.

    triggers:
      - "conversation"
      - "reply thread"
      - "back and forth"

    capture:
      required:
        conversation_id: "Root tweet ID"

      optional:
        reciprocity_signal: "Did we give value before asking for engagement?"
        open_loop: "Did we leave an unanswered question?"
        barrier_level: "How easy is it to reply? (low / medium / high)"
        contribution_invite: "Did we invite others to add their take?"
        controversy_level: "none / mild / strong"
        emotional_arc: "flat / building / peak_and_resolve / cascade"
        turn_taking: "balanced / one_sided / multi_party"

    extraction:
      - field: barrier_level
        keywords:
          low: ["?", "what do you think", "agree or disagree", "drop your"]
          medium: ["explain", "how would you", "what's your take"]
          high: ["prove", "write a", "build", "create", "long form"]
      - field: emotional_arc
        keywords:
          building: ["and then", "but wait", "it gets better", "here's where"]
          peak_and_resolve: ["the turning point", "finally", "the answer", "so here's what"]
          cascade: ["first", "second", "and also", "plus", "on top of that"]

  # Conversation DNA Observer
  - name: conversation_dna
    description: Extracts the DNA pattern from successful conversations

    triggers:
      - "conversation dna"
      - "conversation pattern"
      - "successful thread"

    capture:
      required:
        pattern_type: "hook_and_expand / question_chain / build_together / debate"

      optional:
        hook_style: "What started the conversation"
        escalation_pattern: "How the conversation grew"
        turn_count: "Number of back-and-forth exchanges"
        topic_evolution: "How the topic shifted"
        engagement_curve: "How engagement changed over turns"
        participants: "How many people joined"
        emotional_triggers_used: "Which emotional triggers appeared in the conversation"
        vulnerability_moments: "Moments of genuine uncertainty or admission"
        social_proof_point: "When engagement crossed a threshold and accelerated"

# ============================================================
# LEARNERS: What patterns to detect and learn?
# ============================================================
learners:
  # Reply Effectiveness Learner
  - name: reply_effectiveness
    description: Learns which reply styles generate the best engagement
    type: correlation

    input:
      observer: reply_sent
      fields: [tone_used, hook_type, thread_depth, had_personality_snippet]

    output:
      observer: reply_effectiveness
      fields: [likes, replies_received, author_responded]

    learn:
      - "Which hook types get the most replies"
      - "Which tones work best for different contexts"
      - "Whether personality injection improves engagement"
      - "Optimal thread depth for replies"

    min_samples: 10
    confidence_threshold: 0.65

  # Conversation DNA Learner
  - name: conversation_dna_learner
    description: Learns structural patterns of successful conversations
    type: pattern

    observe: high_engagement_reply_observed

    extract:
      - common_hooks
      - effective_structures
      - tone_patterns
      - topic_compatibility

    correlate_with:
      - parent_tweet_topic
      - time_of_day
      - author_warmth_level

  # Hook Effectiveness Learner
  - name: hook_effectiveness
    description: Learns which opening hooks land best
    type: correlation

    input:
      fields: [hook_type, tone, parent_tweet_topic]

    output:
      fields: [engagement, author_responded, replies_received]

    learn:
      - "Questions vs observations for different topics"
      - "Challenge hooks: when they work vs backfire"
      - "Agreement hooks: genuine vs sycophantic"
      - "Best hooks for technical vs casual contexts"

    min_samples: 8
    confidence_threshold: 0.6

  # Emotional Trigger Effectiveness Learner
  - name: emotional_effectiveness
    description: |
      Learns which emotional triggers drive real engagement.
      Correlates psychological mechanisms with outcomes.
      Goes deeper than tone - understands WHY content resonates.
    type: correlation

    input:
      observer: emotional_trigger
      fields: [primary_trigger, secondary_trigger, trigger_strength]

    output:
      observer: reply_effectiveness
      fields: [likes, replies_received, author_responded, warmth_change]

    learn:
      - "Which emotional triggers generate replies vs likes vs saves"
      - "Whether vulnerability outperforms confidence for engagement"
      - "Optimal trigger combinations (curiosity + validation, surprise + aspiration)"
      - "When strong triggers backfire vs land"
      - "Whether layered triggers outperform single triggers"
      - "Which triggers build relationships vs which build audience"

    min_samples: 15
    confidence_threshold: 0.55

  # Conversation Psychology Learner
  - name: conversation_psychology_learner
    description: |
      Learns the psychological dynamics that make conversations grow.
      Tracks reciprocity, barrier effects, open loops, emotional arcs.
    type: pattern

    observe: conversation_psychology

    extract:
      - optimal_barrier_levels
      - reciprocity_return_rates
      - open_loop_completion_rates
      - emotional_arc_effectiveness
      - controversy_sweet_spot

    correlate_with:
      - topic
      - audience_size
      - time_of_day
      - cultural_mood

# ============================================================
# OUTCOMES: What does success/failure look like?
# ============================================================
outcomes:
  positive:
    - condition: "author_responded == true"
      weight: 1.0
      insight: "Reply started a real conversation"

    - condition: "likes > 5"
      weight: 0.7
      insight: "Reply resonated with audience"

    - condition: "replies_received > 3"
      weight: 0.8
      insight: "Reply sparked wider discussion"

    - condition: "warmth_change == 'increased'"
      weight: 0.9
      insight: "Reply deepened relationship"

    - condition: "quote_tweets > 0"
      weight: 0.6
      insight: "Reply was worth sharing"

  negative:
    - condition: "likes == 0 AND hours_since_reply > 12"
      weight: 0.7
      insight: "Reply got no traction"
      action: analyze_reply_failure

    - condition: "author_responded == false AND warmth == 'cold'"
      weight: 0.5
      insight: "Cold outreach didn't land"
      action: adjust_cold_approach

    - condition: "replies_received > 3 AND sentiment_negative"
      weight: 0.9
      insight: "Reply caused negative reaction"
      action: review_tone_selection

  neutral:
    - condition: "first_reply_to_author"
      insight: "First interaction with this user"
      action: start_warmth_tracking

    - condition: "new_topic_explored"
      insight: "Entered new conversation territory"
      action: observe_reception

# ============================================================
# EVOLUTION: How does this chip improve itself?
# ============================================================
evolution:
  rules:
    - trigger:
        condition: "avg_reply_engagement < 2"
        over: "last_15_replies"
      action: expand_observation
      details:
        add_fields: [parent_tweet_engagement, timing_context, author_audience_size]
        reason: "Low reply engagement suggests missing context"

    - trigger:
        condition: "pattern_validated >= 5"
      action: boost_pattern
      details:
        increase_weight: 0.15
        promote_to: high_confidence

    - trigger:
        condition: "hook_success_rate < 25%"
        over: "last_20_attempts"
      action: deprecate_strategy
      details:
        reason: "Hook type consistently underperforming"
        notify: true

    - trigger:
        condition: "unexpected_engagement_spike"
      action: create_exploratory_learner
      details:
        duration: "7_days"
        auto_promote_if: "generates_3_validated_insights"

  metrics:
    track:
      - avg_reply_engagement
      - author_response_rate
      - hook_success_rate
      - conversation_depth_avg
      - warmth_progression_rate

    goals:
      author_response_rate: "> 30%"
      hook_success_rate: "> 50%"
      conversation_depth_avg: "> 2 turns"

# ============================================================
# CONTEXT CONTRIBUTION
# ============================================================
context:
  format: |
    ## X Conversation Intelligence (Chip: social-convo)

    ### Reply Strategy
    - Best hooks: {{top_hooks}}
    - Best tones: {{top_tones}}
    - Author response rate: {{author_response_rate}}%

    ### Conversation DNA
    {{#each dna_patterns limit=3}}
    - {{pattern_type}}: {{description}} ({{confidence}}% confident)
    {{/each}}

    ### Active Learnings
    {{#each recent_insights limit=5}}
    - {{insight}}
    {{/each}}

  priority: 0.75
  max_chars: 500
