# Vibecoding Chip (runtime)

chip:
  id: vibecoding
  name: Vibecoding Intelligence
  version: 0.2.0
  description: |
    Learns engineering signals from code to outcomes.
    Focuses on quality, velocity, and reliability without harm.
  author: Vibeship
  license: MIT
  human_benefit: "Improve software quality and delivery without harm."
  harm_avoidance:
    - "No deceptive reporting of quality"
    - "No unsafe automation in production"
  risk_level: medium
  safety_tests:
    - "no_false_quality_claims"
    - "no_unsafe_deployments"
  domains:
    - engineering
    - code
    - delivery
    - reliability

triggers:
  patterns:
    - "refactor"
    - "rollback"
    - "flaky test"
    - "latency spike"
    - "incident"
    - "merge"
    - "pull request"
  events:
    - "post_tool"
    - "post_tool_failure"
    - "user_prompt"
    - "PostToolUse"
    - "PostToolUseFailure"
    - "UserPromptSubmit"
    - "code_change"
    - "pr_opened"
    - "test_failed"
    - "deploy_finished"
    - "incident_opened"
  tools:
    - name: Edit
      context_contains:
        - "src/"
        - "lib/"
        - "app/"
        - "tests/"
        - "test/"
        - ".py"
        - ".js"
        - ".tsx"
        - ".go"
        - ".rs"
        - "package.json"
        - "pyproject.toml"
        - "Cargo.toml"
        - "go.mod"
        - "pom.xml"
    - name: Write
      context_contains:
        - "src/"
        - "lib/"
        - "app/"
        - "tests/"
        - "test/"
        - ".py"
        - ".js"
        - ".tsx"
        - ".go"
        - ".rs"
        - "package.json"
        - "pyproject.toml"
        - "Cargo.toml"
        - "go.mod"
        - "pom.xml"
    - name: Read
      context_contains:
        - "src/"
        - "lib/"
        - "app/"
        - "tests/"
        - "test/"
        - ".py"
        - ".js"
        - ".tsx"
        - ".go"
        - ".rs"
        - "package.json"
        - "pyproject.toml"
        - "Cargo.toml"
        - "go.mod"
        - "pom.xml"
    - name: Bash
      context_contains:
        - "pytest"
        - "npm test"
        - "pnpm test"
        - "yarn test"
        - "bun test"
        - "go test"
        - "cargo test"
        - "mvn test"
        - "gradle test"
        - "make test"
        - "lint"
        - "build"
        - "deploy"

observers:
  - name: code_change
    description: Tracks code changes and their scope
    triggers: ["commit", "code change", "diff", "refactor"]
    capture:
      optional:
        repo: "Repository name"
        commit_id: "Commit SHA"
        branch: "Branch name"
        files_changed: "Count of files changed"
        diff_lines: "Lines added/removed"
        file_path: "File path (if available)"
    extraction:
      - field: repo
        patterns:
          - "repo\\s*[:=]\\s*([A-Za-z0-9._/-]+)"
      - field: commit_id
        patterns:
          - "commit(?:_id)?\\s*[:=]?\\s*([a-f0-9]{7,40})"
          - "sha\\s*[:=]\\s*([a-f0-9]{7,40})"
      - field: branch
        patterns:
          - "branch\\s*[:=]\\s*([A-Za-z0-9._/-]+)"
      - field: files_changed
        patterns:
          - "files?\\s*changed\\s*[:=]?\\s*(\\d+)"
      - field: diff_lines
        patterns:
          - "lines?\\s*[:=]?\\s*(\\+?\\d+\\s*/\\s*-?\\d+)"

  - name: ci_failure
    description: Tracks CI/test failures
    triggers: ["test failed", "ci failed", "build failed", "flaky test"]
    capture:
      optional:
        repo: "Repository name"
        test_name: "Failing test identifier"
        error_code: "Error/exception identifier"
        build_id: "Build ID"
        file_path: "File path (if available)"
    extraction:
      - field: repo
        patterns:
          - "repo\\s*[:=]\\s*([A-Za-z0-9._/-]+)"
      - field: test_name
        patterns:
          - "test\\s*[:=]\\s*([A-Za-z0-9._/-]+)"
          - "failing\\s+test\\s+([A-Za-z0-9._/-]+)"
      - field: error_code
        patterns:
          - "error\\s*[:=]\\s*([A-Za-z0-9_]+)"
          - "exception\\s*[:=]\\s*([A-Za-z0-9_]+)"
      - field: build_id
        patterns:
          - "build\\s*[:=]\\s*([A-Za-z0-9_-]+)"

  - name: deploy_event
    description: Tracks deploys and rollbacks
    triggers: ["deploy", "release", "rollback"]
    capture:
      optional:
        repo: "Repository name"
        env: "Environment"
        status: "success/failure"
        release_id: "Release identifier"
        rollback: "true/false"
        file_path: "File path (if available)"
    extraction:
      - field: repo
        patterns:
          - "repo\\s*[:=]\\s*([A-Za-z0-9._/-]+)"
      - field: env
        patterns:
          - "env(?:ironment)?\\s*[:=]\\s*([A-Za-z0-9_-]+)"
      - field: status
        keywords:
          success: ["succeeded", "success", "green"]
          failure: ["failed", "error", "red"]
      - field: release_id
        patterns:
          - "release\\s*[:=]\\s*([A-Za-z0-9_-]+)"
      - field: rollback
        keywords:
          "true": ["rollback", "rolled back"]

outcomes:
  positive:
    - condition: "status == success"
      insight: "Deploy succeeded without rollback"
      weight: 1.0
  negative:
    - condition: "rollback == true"
      insight: "Rollback indicates stability risk"
      weight: 1.0

questions:
  - id: quality_definition
    question: "What does 'quality' mean for this project?"
    category: quality
    phase: discovery
    required: true
    affects_learning: ["ci_failure", "code_change"]
  - id: velocity_tradeoff
    question: "What tradeoffs are acceptable between speed and stability?"
    category: risk
    phase: discovery
    required: false
    affects_learning: ["deploy_event"]
